name: build-and-push

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]

permissions:
  id-token: write   # OIDC
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ECR_REPO:  llm-saas/platform-api  # must match your ECR repo

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::718277288381:role/llm-saas-dev-gha-ecr
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        run: |
          IMAGE="${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPO }}"
          GIT_SHA="${{ github.sha }}"
          docker build -t "$IMAGE:latest" -t "$IMAGE:$GIT_SHA" .
          docker push "$IMAGE:latest"
          docker push "$IMAGE:$GIT_SHA"
